
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-14T12:39:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "59e6369082b1487ad59c525f2424bf147c94cfd6",
 "version": "0.15.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
