
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-16T11:43:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f042ad98f1901a9593722340fe67c36ce2756690",
 "version": "0.18.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
